name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build and Upload Release Assets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            executable_name: PingCraft-linux-amd64
          - os: windows
            arch: amd64
            executable_name: PingCraft-windows-amd64.exe
          - os: darwin
            arch: arm64
            executable_name: PingCraft-macos-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          mkdir -p build
          go build -ldflags="-s -w" -o build/${{ matrix.executable_name }} main.go

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/${{ matrix.executable_name }}
